// packages/svelte/src/lib/NumericText.svelte
<script lang="ts">
  import '@numeric-text/core';
  import { type NumericTextProps, type NumericText as NumericTextElement, BROWSER } from '@numeric-text/core';
  import type { HTMLAttributes } from 'svelte/elements';
  import { onMount, untrack } from 'svelte';

  const {
    value,
    trend,
    transition,
    respectMotionPreference,
    animated = true,
    ...rest
  }: NumericTextProps & HTMLAttributes<HTMLElement> = $props();

  let text = $state<NumericTextElement>()!;
  let isMounted = false;

  $effect(() => {
    text.update(
      value,
      untrack(() => isMounted && animated),
    );
  });

  $effect(() => {
    text.setOptions({ trend, transition, respectMotionPreference });
  });

  onMount(() => {
    isMounted = true;
  });
</script>

<numeric-text bind:this={text} role="img" aria-label={value} {...rest}>
  {BROWSER ? '' : value}
</numeric-text>

// packages/react/src/NumericText.tsx
'use client';

import '@numeric-text/core';
import { type NumericTextProps, type NumericText as NumericTextElement, BROWSER } from '@numeric-text/core';
import { type HTMLAttributes, useLayoutEffect, useRef } from 'react';

type Props = NumericTextProps & HTMLAttributes<HTMLElement>;
const NumericText = ({ value, trend, transition, respectMotionPreference, animated = true, ...rest }: Props) => {
  const ref = useRef<NumericTextElement>(null);
  const isMounted = useRef(false);

  useLayoutEffect(() => {
    if (ref.current) ref.current.update(value, isMounted.current && animated);
    if (!isMounted.current) isMounted.current = true;
  }, [value]);

  useLayoutEffect(() => {
    if (ref.current) ref.current.setOptions({ trend, transition, respectMotionPreference });
  }, [trend, transition, respectMotionPreference]);

  return (
    <numeric-text
      ref={ref}
      role="img"
      aria-label={value + ''}
      {...rest}
      suppressHydrationWarning
      dangerouslySetInnerHTML={{ __html: BROWSER ? '' : value }}
    />
  );
};

export default NumericText;
